### ISSUE TITLE
Investigate transient test failures

### ISSUE THREAD

**Issue by zainab-ali** [zainab-ali/fs2-reactive-streams#33]
The CI build has recently detected some transient test failures:

- `required_spec317_mustSupportACumulativePendingElementCountUpToLongMaxValue`
- `required_spec317_mustSupportAPendingElementCountUpToLongMaxValue`

The stack traces are reproduced here, but don't give too much insight.

```
[info] - required_spec317_mustSupportACumulativePendingElementCountUpToLongMaxValue *** FAILED ***

[info]   java.lang.AssertionError: Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@69678efa to Publisher fs2.interop.reactivestreams.StreamUnicastPublisher@1d9649e4 within 1000 ms

[info]   at org.testng.Assert.fail(Assert.java:89)

[info]   at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:169)

[info]   at org.reactivestreams.tck.TestEnvironment$Promise.expectCompletion(TestEnvironment.java:909)

[info]   at org.reactivestreams.tck.TestEnvironment.subscribe(TestEnvironment.java:245)

[info]   at org.reactivestreams.tck.TestEnvironment.newManualSubscriber(TestEnvironment.java:261)

[info]   at org.reactivestreams.tck.TestEnvironment.newManualSubscriber(TestEnvironment.java:256)

[info]   at org.reactivestreams.tck.PublisherVerification$29.run(PublisherVerification.java:1056)

[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1138)

[info]   at org.reactivestreams.tck.PublisherVerification.required_spec317_mustSupportACumulativePendingElementCountUpToLongMaxValue(PublisherVerification.java:1053)

[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[info]   ...

[info] - required_spec317_mustSupportAPendingElementCountUpToLongMaxValue *** FAILED ***

[info]   java.lang.AssertionError: Could not subscribe org.reactivestreams.tck.TestEnvironment$ManualSubscriberWithSubscriptionSupport@5e2135a3 to Publisher fs2.interop.reactivestreams.StreamUnicastPublisher@788f2f0f within 1000 ms

[info]   at org.testng.Assert.fail(Assert.java:89)

[info]   at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:169)

[info]   at org.reactivestreams.tck.TestEnvironment$Promise.expectCompletion(TestEnvironment.java:909)

[info]   at org.reactivestreams.tck.TestEnvironment.subscribe(TestEnvironment.java:245)

[info]   at org.reactivestreams.tck.TestEnvironment.newManualSubscriber(TestEnvironment.java:261)

[info]   at org.reactivestreams.tck.TestEnvironment.newManualSubscriber(TestEnvironment.java:256)

[info]   at org.reactivestreams.tck.PublisherVerification$28.run(PublisherVerification.java:1038)

[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1138)

[info]   at org.reactivestreams.tck.PublisherVerification.required_spec317_mustSupportAPendingElementCountUpToLongMaxValue(PublisherVerification.java:1035)

[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[info]   ...
```
```
[info] - stochastic_spec103_mustSignalOnMethodsSequentially *** FAILED ***

[info]   java.lang.AssertionError: Failed in iteration 0 of 100. Expected completion signal after signalling 10 elements (signalled 0), yet did not receive it within 10000 ms

[info]   at org.testng.Assert.fail(Assert.java:89)

[info]   at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:169)

[info]   at org.reactivestreams.tck.TestEnvironment$Latch.expectClose(TestEnvironment.java:841)

[info]   at org.reactivestreams.tck.PublisherVerification$5$1.run(PublisherVerification.java:347)

[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1138)

[info]   at org.reactivestreams.tck.PublisherVerification$5.apply(PublisherVerification.java:258)

[info]   at org.reactivestreams.tck.PublisherVerification$5.apply(PublisherVerification.java:255)

[info]   at org.reactivestreams.tck.PublisherVerification.stochasticTest(PublisherVerification.java:1207)

[info]   at org.reactivestreams.tck.PublisherVerification.stochastic_spec103_mustSignalOnMethodsSequentially(PublisherVerification.java:255)

[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by zainab-ali** [comment]
Another bug was detected in a recent build:
```
[info] PublisherToSubscriberSpec:

[info] - should have the same output as input *** FAILED ***

[info] TestFailedException was thrown during property evaluation.

[info] Message: Vector(452749735, 0, -2147483648, -221720488, 690052367, -645016783, 2147483647) did not equal Vector(452749735, 0, -2147483648, -221720488, 690052367, -645016783, 2147483647, -1151558)

[info] Location: (PublisherToSubscriberSpec.scala:19)

[info] Occurred when passed generated values (

[info] arg0 = Vector(452749735, 0, -2147483648, -221720488, 690052367, -645016783, 2147483647, -1151558) // 1 shrink

[info] )
```

**Comment by zainab-ali** [comment]
These couldn't be reproduced before.  It would be worth checking up on them now that the subscription design has changed.

**Comment by pepegar** [comment]
Hi!

we're using fs2-reactive-streams in
[freestyle-rpc](https://github.com/frees-io/freestyle-rpc) and we're
facing some failures similar to the ones you describe in this ticket
(https://github.com/frees-io/freestyle-rpc/issues/289).  We're not
completely sure that they're related to this, however, we're just
guessing and investigating the root cause of them.

Have you found the root cause of this, or how to fix it?

Cheers, thanks for the library!

**Comment by zainab-ali** [comment]
Hi @pepegar!  Thanks for bringing this up.  The test failures were largely fixed by the bugfixes in #48.  It's unlikely that they're the cause, but the problem could still be related to fs2-reactive-streams.  I'll dig into it and see what I can find.

You mentioned correctly that only unicast publishers are supported.  Are you using the library in a way that needs multicast?

**Comment by pepegar** [comment]
Hey @zainab-ali, sorry for the delay!

I think we do not need more than one subscriber per publisher, but some an error message from one of our test failures suggested something along those lines (I cannot find the issue now, we talked about it in person).

I'm planning to investigate this a bit further at the end of this week, so I'll keep you posted with my findings.
