### ISSUE TITLE
Update to cats-effect 1.0.0-RC3

### ISSUE THREAD

**Issue by adamw** [zainab-ali/fs2-reactive-streams#52]
I'm seeing this error after updating:

```
java.lang.NoSuchMethodError: cats.effect.Timer.shift()Ljava/lang/Object;
	at fs2.async.package$.unsafeRunAsync(async.scala:132)
	at fs2.interop.reactivestreams.StreamUnicastPublisher.subscribe(StreamUnicastPublisher.scala:30)
	at org.asynchttpclient.netty.request.body.NettyReactiveStreamsBody.write(NettyReactiveStreamsBody.java:60)
```

**Comment by zainab-ali** [comment]
Thanks!  Release 0.7.0 upgrades to fs2 1.0.0-M4 and consequently cats-effect 1.0.0-RC3.  This should now be fixed.

**Comment by adamw** [comment]
Thanks :)
