### ISSUE TITLE
Transient test failure in StreamUnicastPublisherSpec - required_spec303_mustNotAllowUnboundedRecursion

### ISSUE THREAD

**Issue by zainab-ali** [zainab-ali/fs2-reactive-streams#53]
Discovered in the [2.11 Travis build](https://travis-ci.org/zainab-ali/fs2-reactive-streams/jobs/424445640):

```
[info] - required_spec303_mustNotAllowUnboundedRecursion *** FAILED ***
[info]   java.lang.AssertionError: Unable to validate call stack depth safety, awaited at-most 2 signals (`maxOnNextSignalsInRecursionTest()`) or completion within 1000 ms
[info]   at org.testng.Assert.fail(Assert.java:89)
[info]   at org.reactivestreams.tck.TestEnvironment.flop(TestEnvironment.java:169)
[info]   at org.reactivestreams.tck.TestEnvironment$Latch.expectClose(TestEnvironment.java:852)
[info]   at org.reactivestreams.tck.PublisherVerification$19.run(PublisherVerification.java:819)
[info]   at org.reactivestreams.tck.PublisherVerification.activePublisherTest(PublisherVerification.java:1138)
[info]   at org.reactivestreams.tck.PublisherVerification.required_spec303_mustNotAllowUnboundedRecursion(PublisherVerification.java:752)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[info]   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[info]   at java.lang.reflect.Method.invoke(Method.java:498)
```

This failure looks to be a new one.

**Comment by zainab-ali** [comment]
I can't get this to fail locally, even when running 1000 times.  I'm going to try and replicate it once again on Travis.

**Comment by zainab-ali** [comment]
I've ran this at least 1000000 times locally and can't reproduce it.  Oddly enough, it also hasn't been reproduced since on Travis.
